### ISSUE TITLE
After put data/config.json, there is no effect.

### ISSUE THREAD

**Issue by kalsolio** [jandrassy/arduino-firmware-wifilink#1]
I add a right config.json in data/config.json. After Upload like this, My uno wifi board has no ip address.
![001](https://user-images.githubusercontent.com/14342288/34508533-752090ca-f07b-11e7-8ab1-1ec1e5ca4c2a.png)
![002](https://user-images.githubusercontent.com/14342288/34508535-7d037cf8-f07b-11e7-8710-e04e84248d74.png)

**Comment by kalsolio** [comment]
I put ssid and password into config.json

**Comment by kalsolio** [comment]
After set ssid and password by webpanel, ReUpload SPIFFS also have no effect, I can saw the last setting info, not the setting by config.json file.

**Comment by kalsolio** [comment]
I found this.
WiFi.begin(); // connect to AP with credentials remembered by esp sdk

**Comment by JAndrassy** [comment]
sorry, I [changed it](https://github.com/jandrassy/arduino-firmware-wifilink/commit/36d8ce250ae4575e27f738c2117f1a1efcc16625#diff-04c6e90faac2675aa89e2176d2eec7d8) recently
