### ISSUE TITLE
Uno WiFi Dev Edition

### ISSUE THREAD

**Issue by Damianoux** [jandrassy/arduino-firmware-wifilink#12]
HI,
I have a problem with Arduino Uno Wifi Dev Edition (Rev1).
In installed the firmware and everything works, except for te fact that mDNS doen not start on boot.
I cannot discover until I change the hostname in the web panel.
After doing this the device is discoverable and I can program OTA.
On the next reboot mDNS does not work  and I need repeat the procedure to program once again.

**Comment by JAndrassy** [comment]
Hi. what version of esp8266 Arduino did you use to build the firmware?

**Comment by Damianoux** [comment]
Hi,
Should be 2.7.1.
FYI I found  that  I can flash multiple times from arduino ide (1.8.12), once it discovers the board over wifi, even if mdns deisapperas on the first reboot. It works  until I close the IDE. Then I have to go to web panel and change the hostname for the board to be rediscovered. I also get the message that the board can't be reset after uploading sketch OTA , but the sketch is uploaded and the board reboots correctly.
Seems that changing hostname starts mdns, but it is not started on boot.

**Comment by JAndrassy** [comment]
try in setup() of the firmware disabling the MDNS start by OTA library
`ArduinoOTA.begin(false);`
to not be in conflict by MDNS initialised by the firmware sketch

**Comment by Damianoux** [comment]
Hi jandrassy,
No it didn't work by disabling ArduinoOTA.begin in setup(), but maybe I found a different arrangement. It seems that setup() tries to initializa mDNS before WIFI has started.
So I moved all initialization in loop(), checking that WiFi.status() is connected before.
If you are interested in PR i will test it for a while than i will push changes on my fork.

**Comment by JAndrassy** [comment]
this https://github.com/jandrassy/arduino-firmware-wifilink/commit/401af1d75965b3dc469dfc4c6ccae07965a48c31 ?

**Comment by Damianoux** [comment]
Didn't try this.
I delay all initializations until wifi is available. Seems To work for Now. If It does Not have any Side effect in The Next few days i Will push The changes.
But Now after powering The board i immediately Can See The wifi Port.

**Comment by JAndrassy** [comment]
setWiFiConfig() does the WiFi setup and waits for the connection

**Comment by Damianoux** [comment]
So moving initMDNS after setWiFiConfig should start mdns after the connection has been estabilished?
I will try this as soon as I have the time.
