### ISSUE TITLE
ArduinoJson 6 updated needed

### ISSUE THREAD

**Issue by w1r3d90d** [jandrassy/arduino-firmware-wifilink#15]
ArduinoJson 6 updated needed
That's all

**Comment by JAndrassy** [comment]
Hi. do you use this firmware? Why?

**Comment by w1r3d90d** [comment]
Well I was trying to.  I need ArduinoOTA ability with a standard Arduino Uno.  I have plenty of esp8266-01 boards and this project seemed to fit the need perfectly.  I was able to get around the JSON issue but I now cannot get the SPIFFS data to load.  I think the esp-01 doesn’t have enough flash for the project binary and SPIFFS to fit.

**Comment by JAndrassy** [comment]
if you use Linux, you can use this to upload to Uno with esp8266
https://github.com/jandrassy/lab/blob/master/AvrDudeTelnet/AvrDudeTelnet.ino

or you could try
https://github.com/jeelabs/esp-link

**Comment by w1r3d90d** [comment]
Thanks
I could probably use either of those.  
Thanks
