### ISSUE TITLE
which version of ArduinoJson should I choose?

### ISSUE THREAD

**Issue by kalsolio** [jandrassy/arduino-firmware-wifilink#3]
https://github.com/bblanchon/ArduinoJson/releases

I saw a lot of BREAKING CHANGES, which version should I choose?

**Comment by JAndrassy** [comment]
any 5.x.x should be OK. it is used only to create an read configuration file config.json. if it compiles it will work. right now I do not know which version I used in my latest firmware build a month ago, because I by mistake deleted ArduinoJson from libraries folder
