### ISSUE TITLE
ESP-03

### ISSUE THREAD

**Issue by jfmateos** [jandrassy/arduino-firmware-wifilink#6]
Dear Jandrassy,

Could I use this project with an ESP-03? It only has 512Kbytes, so the max SPIFF size is 128Kbytes, but I read that the ESP8266 filesystem uploader needs at least 512kB.

Thanks and kind regards from madrid

**Comment by JAndrassy** [comment]
try to use it without SPIFFS. Set SSID and password in sketch with WiFiLink library. Most of the examples of  the WiFiLink library are without WiFi.begin(), but you can add it like in the ConnectWithWPA.ino example.

**Comment by jfmateos** [comment]
Thanks, You put me on the way.
I have managed to get port 192.168.1.140 in the Arduino IDE.
I have cofigured the board as "Arduino Uno WiFi" (in fact it is a bare atmega328p with minicore bootloader).
I have connected:
RX from ESP-03 to TX on Atmeta328p
TX from ESP-03 to RX on Atmeta328p
GPIO0 from ESP-03 to Reset on Atmega 328p

But I get the following error:
https://i.paste.pics/6096385882ec9b4a1a4380bd86fac892.png

**Comment by jfmateos** [comment]
The minicore in the Atmega328p is configured with an external 8MHz clock

**Comment by JAndrassy** [comment]
you have Optiboot with custom frequency and baud rate in the ATmega?
try to set DEFAULT_BAUD in esp8266-serial.c in dfu library

**Comment by jfmateos** [comment]
Nice it worked. Thank you very much Jandrassy.

https://i.paste.pics/fbf514580dbf7b6924a88a1cbf3e9ff6.png

The baud rate for minicore 328p 8MHz was 38400.

Nevertheless, I have found esp-03 boards with 1MB... so I will try again with SPIFFS.

**Comment by JAndrassy** [comment]
btw my name is [Juraj](https://github.com/jandrassy).
